#define BOOST_TEST_MODULE load_of_tests


#include <boost/test/included/unit_test.hpp>

BOOST_AUTO_TEST_CASE(mass_test)
{
    int i = 8;
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
    BOOST_CHECK_EQUAL(#LINE, ++i);
}