language: cpp
compiler:
  - gcc

os:
  - linux

addons:
  apt:
    packages:
      - libboost-test-dev
      - cmake

script:
  - mkdir build &&  cd build
  - cmake ..
  - cmake --build . -- -j4 2> build.log
  - cat build.log
  - cd test
  - ctest . -C Debug -V

after_failure:
  - curl -s https://raw.githubusercontent.com/report-ci/scripts/master/annotate.py | python - --tool gcc --input build.log

after_script:
  - python <(curl -s https://raw.githubusercontent.com/report-ci/scripts/master/upload.py)